"""empty message

Revision ID: 200b9d466de4
Revises: b928cafdd50e
Create Date: 2018-02-03 14:13:44.877200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200b9d466de4'
down_revision = 'b928cafdd50e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'id')
    # ### end Alembic commands ###
