"""empty message

Revision ID: 38120a2f9141
Revises: 
Create Date: 2018-01-28 14:55:17.254235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38120a2f9141'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emil', sa.String(length=100), nullable=False),
    sa.Column('translatorname', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emil', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('translator')
    # ### end Alembic commands ###
