"""empty message

Revision ID: 5caf11ab18ac
Revises: 77141e52b3b9
Create Date: 2018-02-01 21:41:38.440316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5caf11ab18ac'
down_revision = '77141e52b3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('title', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'title')
    # ### end Alembic commands ###
