"""empty message

Revision ID: 77141e52b3b9
Revises: 38120a2f9141
Create Date: 2018-02-01 18:12:31.751968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77141e52b3b9'
down_revision = '38120a2f9141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
