"""empty message

Revision ID: 7b04e8ad19ad
Revises: 200b9d466de4
Create Date: 2018-02-03 21:18:12.214290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b04e8ad19ad'
down_revision = '200b9d466de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 're_translated',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('article', 'translated',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'translated',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('article', 're_translated',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
