"""empty message

Revision ID: 910af2beb0d3
Revises: 136db5146cc5
Create Date: 2018-02-06 14:29:13.978424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910af2beb0d3'
down_revision = '136db5146cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'price')
    # ### end Alembic commands ###
