"""empty message

Revision ID: a5173deaef7c
Revises: 7b04e8ad19ad
Create Date: 2018-02-03 22:08:38.170128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5173deaef7c'
down_revision = '7b04e8ad19ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('translated', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('article', 're_translated',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('article', 'translated',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'translated',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('article', 're_translated',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_table('result')
    # ### end Alembic commands ###
