"""empty message

Revision ID: aae8c5a7a2c3
Revises: 4c83b08af65c
Create Date: 2018-02-06 18:02:26.558025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae8c5a7a2c3'
down_revision = '4c83b08af65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('person', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'person')
    # ### end Alembic commands ###
