"""empty message

Revision ID: b60c62d8c77c
Revises: f12392cd8625
Create Date: 2018-02-06 15:40:09.935616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60c62d8c77c'
down_revision = 'f12392cd8625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translator', sa.Column('all_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translator', 'all_time')
    # ### end Alembic commands ###
