"""empty message

Revision ID: b928cafdd50e
Revises: 5caf11ab18ac
Create Date: 2018-02-02 13:13:40.695931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b928cafdd50e'
down_revision = '5caf11ab18ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('paragraph_name', sa.String(length=50), nullable=False))
    op.add_column('article', sa.Column('re_translated', sa.Text(), nullable=True))
    op.add_column('article', sa.Column('translated', sa.Text(), nullable=True))
    op.drop_column('article', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    op.drop_column('article', 'translated')
    op.drop_column('article', 're_translated')
    op.drop_column('article', 'paragraph_name')
    # ### end Alembic commands ###
