"""empty message

Revision ID: cc01bfae3036
Revises: aae8c5a7a2c3
Create Date: 2018-02-06 19:45:02.661339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc01bfae3036'
down_revision = 'aae8c5a7a2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'translated')
    op.drop_column('result', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('content', mysql.TEXT(), nullable=False))
    op.add_column('result', sa.Column('translated', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
