"""empty message

Revision ID: f12392cd8625
Revises: 910af2beb0d3
Create Date: 2018-02-06 15:03:03.470636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12392cd8625'
down_revision = '910af2beb0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translator', sa.Column('money', sa.Float(), nullable=False))
    op.add_column('translator', sa.Column('pay', sa.String(length=150), nullable=True))
    op.add_column('translator', sa.Column('right', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translator', 'right')
    op.drop_column('translator', 'pay')
    op.drop_column('translator', 'money')
    # ### end Alembic commands ###
